### ISSUE TITLE
Where can I access the updated data with PD GWAS of year 2020?

### ISSUE THREAD

**Issue by rmd13** [grennfp/GWAS_locus_browser#2]
May I ask where can I access the updated github repository  with PD GWAS of year 2020?

**Comment by grennfp** [comment]
Which 2020 GWAS are you referring to? https://pubmed.ncbi.nlm.nih.gov/31701892/ remains the latest PD case control GWAS. 

This repo is a few commits behind the current version of the browser so I will work to update this repo in the next couple of weeks.

**Comment by rmd13** [comment]
Hi,  yes, the online browser has some new GWAS data recently added.

By the way, I found that this repo has several loci duplicated(using alternative snp name, but indeed the same locus), 

I found that there are total 83 unique loci in this repo, less than 90 loci from Nalls, 2019. 
Are the missing loci not included in the repo and GWAS browser?

Below  is the list of name of redundant loci I found.
rs6825004.png
rs4101061.png
rs356182.png
rs117896735.png
rs117615688.png
rs114138760.png
rs35749011.png
rs34637584.png
rs34311866.png
rs11557080.png
rs10221156.png

The rest unique loci add up to 83:
Loci_01_rs10513789_locus.jpg
Loci_02_rs10748818_locus.jpg
Loci_03_rs10756907_locus.jpg
Loci_04_rs10797576_locus.jpg
Loci_05_rs10847864_locus.jpg
Loci_06_rs11150601_locus.jpg
Loci_07_rs11158026_locus.jpg
Loci_08_rs112485576_locus.jpg
Loci_09_rs11578699_locus.jpg
Loci_10_rs11610045_locus.jpg
Loci_11_rs11658976_locus.jpg
Loci_12_rs11683001_locus.jpg
Loci_13_rs11707416_locus.jpg
Loci_14_rs11950533_locus.jpg
Loci_15_rs12147950_locus.jpg
Loci_16_rs12283611_locus.jpg
Loci_17_rs12456492_locus.jpg
Loci_18_rs12497850_locus.jpg
Loci_19_rs12528068_locus.jpg
Loci_20_rs12600861_locus.jpg
Loci_21_rs1293298_locus.jpg
Loci_22_rs12951632_locus.jpg
Loci_23_rs13117519_locus.jpg
Loci_24_rs13294100_locus.jpg
Loci_25_rs1450522_locus.jpg
Loci_26_rs1474055_locus.jpg
Loci_27_rs1867598_locus.jpg
Loci_28_rs1941685_locus.jpg
Loci_29_rs199351_locus.jpg
Loci_30_rs2042477_locus.jpg
Loci_31_rs2086641_locus.jpg
Loci_32_rs2248244_locus.jpg
Loci_33_rs2251086_locus.jpg
Loci_34_rs2269906_locus.jpg
Loci_35_rs2280104_locus.jpg
Loci_36_rs246814_locus.jpg
Loci_37_rs26431_locus.jpg
Loci_38_rs2904880_locus.jpg
Loci_39_rs3104783_locus.jpg
Loci_40_rs34025766_locus.jpg
Loci_41_rs3742785_locus.jpg
Loci_42_rs3802920_locus.jpg
Loci_43_rs382940_locus.jpg
Loci_44_rs4140646_locus.jpg
Loci_45_rs4653767_locus.jpg
Loci_46_rs4698412_locus.jpg
Loci_47_rs4771268_locus.jpg
Loci_48_rs5019538_locus.jpg
Loci_49_rs55818311_locus.jpg
Loci_50_rs55961674_locus.jpg
Loci_51_rs57891859_locus.jpg
Loci_52_rs61169879_locus.jpg
Loci_53_rs61863020_locus.jpg
Loci_54_rs620513_locus.jpg
Loci_55_rs62053943_locus.jpg
Loci_56_rs62333164_locus.jpg
Loci_57_rs6476434_locus.jpg
Loci_58_rs6497339_locus.jpg
Loci_59_rs6500328_locus.jpg
Loci_60_rs6658353_locus.jpg
Loci_61_rs666463_locus.jpg
Loci_62_rs6808178_locus.jpg
Loci_63_rs6854006_locus.jpg
Loci_64_rs7134559_locus.jpg
Loci_65_rs72840788_locus.jpg
Loci_66_rs73038319_locus.jpg
Loci_67_rs75859381_locus.jpg
Loci_68_rs76116224_locus.jpg
Loci_69_rs76763715_locus.jpg
Loci_70_rs76904798_locus.jpg
Loci_71_rs76949143_locus.jpg
Loci_72_rs77351827_locus.jpg
Loci_73_rs7938782_locus.jpg
Loci_74_rs8087969_locus.jpg
Loci_75_rs823118_locus.jpg
Loci_76_rs850738_locus.jpg
Loci_77_rs873786_locus.jpg
Loci_78_rs896435_locus.jpg
Loci_79_rs9261484_locus.jpg
Loci_80_rs9568188_locus.jpg
Loci_81_rs9638616_locus.jpg
Loci_82_rs979812_locus.jpg
Loci_83_rs997368_locus.jpg

**Comment by rmd13** [comment]
I would like to know for each SNP the PD risk is decreased or increased. Is there a way to get the odds ratio for each SNP of each loci listed in the browser, or is this information stored in the repo?

 From the json file I can only extract the log-10p, SNP chromosome location, ref and alt nucleotide, but cannot get the rs* label and odds ratio for each snp.

**Comment by grennfp** [comment]
yes so Nalls et al. 2019 identified 90 unique PD risk variants. We assign each of these 90 to a locus number. Multiple variants can get assigned to one locus if they are within 1MB of each other (ex: locus 1 has three Nalls et al. variants assigned to it, locus 4 has two Nalls et al. variants assigned to it, etc). So that makes 78 risk loci from Nalls et al. with 90 risk variants. +2 risk loci/variants from Foo et al. and +2 risk loci/variants from Iwaki et al. So I believe it should come to a total of 82 risk loci. 

The data you are looking for can be found here: https://github.com/grennfp/GWAS_locus_browser/blob/master/www/summarystats/META5Loci.csv

Foo et al. Asian GWAS data is in AsianLoci.csv
Iwaki et al. Progression GWAS data is in ProgressionLoci.csv

**Comment by grennfp** [comment]
updated the repo with most recent code and data so I will close this issue.
